name: GitOps Workflow

on:
  push:
    branches:
      - main

jobs:
  provision_eks:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout Terraform code
        uses: actions/checkout@v3
        with:
          repository: Ahmed-Bechahed/myapp-eks-terraform  
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ToDo-App/

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve


  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: |
          version="build-${{ github.run_number }}"
          echo "Docker tag: $version"
          docker build -t jlayl/todo-app:$version .
          docker push jlayl/todo-app:$version

  update_manifest:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: Ahmed-Bechahed/myapp-kube-manifest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "bechahedahmed24@gmail.com"
          git config --global user.name "Ahmed-Bechahed"

      - name: Update Manifest File
        run: |
          TAG=${{ github.run_number }}
          ((TAG--))  # Adjust tag to match previous build
          sed -i "s/build-.*/build-$TAG/g" deployment.yaml
          cat deployment.yaml

      - name: Commit and Push Changes
        run: |
          git add manifest/deployment.yaml
          git commit -m "new build with imgTag build-$TAG"
          git push https://${{ secrets.GITHUB_PERSONAL_TOKEN }}@github.com/Ahmed-Bechahed/myapp-kube-manifest.git
